# application: reset
# version: 1
runtime: java21
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: .*
  script: auto